# Rôle : Déclare toutes les routes disponibles dans l'application.
# Fonctionnement :
# Liste les chemins (URI) associés à des méthodes HTTP (GET, POST, etc.).
# Associe chaque route à une "action" dans un contrôleur (ex. : Mini\Controller\IndexAction).

routes:
  # Exemple de route :
  "/":
    method: GET
    callable: App\Controller\HomeController::index

  /a-propos:
    method: GET
    callable: App\Controller\AboutController::index

  "/registration":
    method: GET|POST
    callable: App\Controller\RegisterController::register

  # "/news/:id":
  #   method: GET
  #   callable: App\Controller\NewsController::show
