<section class="register-container">
    <div class="register-left">
        <h1>Inscription</h1>

        <form action="<?= $this->url('auth/registration') ?>" method="POST" class="form">
            <label for="username">Nom d'utilisateur</label>
            <input type="text" id="username" name="username" required>

            <label for="email">Adresse email</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password" required>

            <button type="submit" class="btn-green">S’inscrire</button>
        </form>

        <p class="register-alt">Déjà inscrit ? <a href="<?= $this->url('auth/login') ?>">Connectez-vous</a></p>
    </div>

</section>